### PR TITLE
fix bugs background in refresh

### PR DESCRIPTION
**Pull request by djay**

### CODE REVIEW

**Comment by djay** [comment]
@drinfernoo  I suspect a line you put in already fixes #58 .
```
 hash = hashlib.sha1(six.text_type(path)).hexdigest()
```
just the old line wasn't removed?

**Comment by drinfernoo** [comment]
Ah, I suspect you're right. I must've bungled that merge 🤦 I had a feeling that we'd run into a few of these weird little Unicode bugs and such, but they always end up coming out of the woodwork 😉

Is this one ready to go then?

**Comment by djay** [comment]
@drinfernoo I think so. I don't know of any other bugs

**Comment by djay** [comment]
@drinfernoo I am seeing a couple of exceptions reading the .cache json files.
```
Expecting property name enclosed in double quotes: line 1583 column 1 (char 62797)
```

```
 'NoneType' object is not callable
```

**Comment by drinfernoo** [comment]
I feel like this is fixed now?

**Comment by drinfernoo** [comment]
Hey, I think it would be a good time to try to punch these through 😉

**Comment by djay** [comment]
Generally has been working well for me. I need to get it reinstalled on matrix with an auramod clone to test again.

**Comment by drinfernoo** [comment]
Of course. I recognize that these haven't been touched in awhile, either... so may be worth rebasing just to be safe.

**Comment by drinfernoo** [comment]
I recently rewrote the `utils.cache_files(...)` method anyways, so that hunk was unneeded, but `develop` now has the fix for threading as well.

**Pull request closed without merging**
