### PR TITLE
background refresh of widgets after playback

### PR DESCRIPTION
**Pull request by djay**
will also save widget ids to the .history files

### CODE REVIEW

**Comment by djay** [comment]
@drinfernoo currently having an issue that the logging I'm doing in the monitor service doesn't seem to be appearing in the log, whereas the code is being executed. Seen anything like that before?

**Comment by drinfernoo** [comment]
Did you pull the change from here: https://github.com/drinfernoo/plugin.program.autowidget/blob/2180ff07b78a6f3aac40fc898ad59c2551f68e2e/plugin.program.autowidget/resources/lib/common/utils.py?

**Comment by djay** [comment]
@drinfernoo I didn't see anything in the diff but it is indeed working now. It does seem to be working ok for me in some basic testing. its not smart. After any media stops it refreshes everything thats been refreshed since startup. If its too much updates we can optimise it later?
I've change to the PR to develop. Want to test?

**Comment by djay** [comment]
@drinfernoo ready for testing. Any idea why the conflict diffs are so useless? Is it some tabs vs spaces thing or some automatic reformatting?

**Comment by djay** [comment]
Results on my firestick are
- startup - 2020-11-04 10:23:56.189
- first cache read - 2020-11-04 10:24:34.490
- first cache worker processing - 2020-11-04 10:25:14.626
- when first dequeued is reread - 2020-11-04 10:25:29.975
- when first queued is reread - 2020-11-04 10:26:52.204

So 3min to start getting updated widgets and maybe 40s to get start getting cached widgets. Feels like longer than this so maybe it's not requesting the top visible one first?

I can see one issue looking at the logs. If a path is accessed twice its requeued so goes down the priority list. Should be easy to fix. Not sure why things are accessed more than once during loading.

**Comment by djay** [comment]
@drinfernoo after the latest rebase I get the following error

```
2020-11-04 21:15:50.250 T:30569   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: Invalid setting type
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.autowidget/main.py", line 3, in <module>
                                                from resources.lib.common import router
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.autowidget/resources/lib/common/router.py", line 7, in <module>
                                                from resources.lib import edit
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.autowidget/resources/lib/edit.py", line 11, in <module>
                                                advanced = utils.get_setting_bool('context.advanced')
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.autowidget/resources/lib/common/utils.py", line 310, in get_setting_bool
                                                return _addon.getSettingBool(setting)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.kodi-six/libs/kodi_six/utils.py", line 62, in wrapper
                                                return py2_decode(func(*mod_args, **mod_kwargs),
                                            TypeError: Invalid setting type
                                            -->End of Python script error report<--
```

**Comment by drinfernoo** [comment]
Which branch did you rebase? I'll have to look into it. And... no, I'm not sure why the diffs here are so worthless 😅

**Comment by djay** [comment]
@drinfernoo the develop branch

**Comment by drinfernoo** [comment]
Ok, for now I've merged to `develop`, and the corresponding release is 0.0.1080. Keep in mind that (for some reason) the actual version number is always *one less* than what it says in the commit message, and also that since basically *any* push generates a release, there is no certainty that a higher version contains the same code.

**Pull request merged**
