### PR TITLE
Add spanish translation [es_ES]

### PR DESCRIPTION
**Pull request by roliverosc-zz**

### CODE REVIEW

**Comment by drinfernoo** [comment]
Is this pretty much ready to go? I can merge it in time for 1.6.0 😉

**Comment by drinfernoo** [comment]
I'm going to go ahead and merge this. If it isn't complete by the time I do, feel free to submit further PRs.

**Comment by roliverosc-zz** [comment]
It is ready. Thank you and wonderful add-on.

**Comment by drinfernoo** [comment]
¡Gracias!

Am I doing everything right for you to be able to translate? Can I do anything differently to make future translations easier?

**Comment by roliverosc-zz** [comment]
Update any changes in strings.po en_GB in es_ES also. That would be perfect and helpful.
Thanks to you @drinfernoo.

**Pull request merged**
